@Catalog_HostAddress = https://localhost:7098/products

### Get All Products
GET {{Catalog_HostAddress}}/
Accept: application/json

### Get Product by ID
GET {{Catalog_HostAddress}}/1
Accept: application/json

### Create a New Product
POST {{Catalog_HostAddress}}/
Content-Type: application/json

{
    "id": 10,
    "name": "New Product",
    "description": "This is a new product",
    "price": 19.99,
    "imageUrl": "product-image.jpg"
}

### Update an Existing Product
PUT {{Catalog_HostAddress}}/10
Content-Type: application/json

{
    "id": 10,
    "name": "Updated Product",
    "description": "This is an updated product",
    "price": 29.99,
    "imageUrl": "updated-product-image.jpg"
}

### Update an Existing Product
PUT {{Catalog_HostAddress}}/1
Content-Type: application/json

{
    "id": 10,
    "name": "Updated Product 1",
    "description": "This is an updated product",
    "price": 5.98,
    "imageUrl": "updated-product-image.jpg"
}

### Delete a Product
DELETE {{Catalog_HostAddress}}/10
Content-Type: application/json

### Support Query using AI
GET {{Catalog_HostAddress}}/support/give-me-one-product-recommendation
Accept: application/json

###
GET {{Catalog_HostAddress}}/search/Hiking
Accept: application/json

###
GET {{Catalog_HostAddress}}/aisearch/prive_above_50
Accept: application/json